{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "7 1"
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SubSectionHeadingBreak}
  \i{@Num @@V @SubSectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SubSectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SubSectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SubSectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @SectionShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{No}
  newpage{No}
@@V @Body} } }
 }
{@@E {
{ @@A { @@E {
@@D "544 33"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1227.cap/magw/leptones.1"}
  \b{@@V @ShortNum}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "544 33"
}
{@@V @ContentsStuff} } }
}
{Yes @@V @ContentsEntry
  \a{@@V contentsindent}
  \b{"10.1227.cap/magw/leptones.1"}
  \c{@@V @LongNum}
  \d{@@V initiallanguage @Language @@V title}
  \e{@PageOf "10.1227.cap/magw/leptones.1"}} } }
}
{@@V @SendContents @@V @ContentsItem
  \a{@@V indent}
  \b{"10.1227.cap/magw/leptones.1"}
  \c{@@V number}
  \d{@@V title}
  \e{@@V pagenum}
  \f{@@V pregap}
  \g{@@V postgap}}}

{@@E {
@@D "544 33"
}
{@TitleMarker
  \a{"10.1227.cap/magw/leptones.1"}
  \b{@@V title}}}

{@@E {
@@D "49 4"
}
{@@V @SubSubSectionList
  \a{"10.290.cap/magw/leptones.1"}
1}}

{@@E {
{ @@A { @@E {
@@D "7 1"
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ @LInput }} } }
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.1"}
  \b{Ecuación radial y ecuación angular}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "2047 119"
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.1"}
  \b{Ecuación radial y ecuación angular}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1258.cap/magw/leptones.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Slope}
  \h{@@V @SubSubSectionHeadingBreak}
  \i{@Num @@V @SubSubSectionHeadingFormat @Body}
  \k{No}
  \l{@@V @SubSubSectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SubSubSectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SubSubSectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @SubSectionShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{No}
  newpage{No}
@@V @Body} } }
 }
{@@E {
{ @@A { @@E {
@@D "2319 133"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1258.cap/magw/leptones.1"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "2319 133"
}
{@TitleMarker
  \a{"10.1258.cap/magw/leptones.1"}
  \b{@@V title}}}

{@@E {
@@D "63 5"
}
{{} @@V @SendRef mclachlan}}

{@@E {
@@D "49 4"
}
{@@V @SubSubSectionList
  \a{"10.290.cap/magw/leptones.2"}
2}}

{@@E {
@@D "2047 119"
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.2"}
  \b{Visión intuitiva de las posibles soluciones.}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "2047 119"
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.2"}
  \b{Visión intuitiva de las posibles soluciones.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1258.cap/magw/leptones.2"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Slope}
  \h{@@V @SubSubSectionHeadingBreak}
  \i{@Num @@V @SubSubSectionHeadingFormat @Body}
  \k{No}
  \l{@@V @SubSubSectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SubSubSectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SubSubSectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @SubSectionShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{No}
  newpage{No}
@@V @Body} } }
 }
{@@E {
{ @@A { @@E {
@@D "3573 209"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1258.cap/magw/leptones.2"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "3573 209"
}
{@TitleMarker
  \a{"10.1258.cap/magw/leptones.2"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
@@D "2047 119"
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.2"}
  \b{Visión intuitiva de las posibles soluciones.}
{ @LInput }} } }
}
{@Table
  \a{"9.4052.cap/magw/leptones.1"}
  \b{Funciones radiales de Mathieu}
{}}}

{@@E {
@@D "4557 265"
}
{@Table
  \a{"9.4052.cap/magw/leptones.2"}
  \b{Funciones angulares de Mathieu}
{}}}

{@@E {
{ @@A { @@E {
@@D "63 5"
}
{@@V @TableCounterIncrement "9.4052.cap/magw/leptones.1"} } }
}
{@@V @TableCounterMarker
  \a{"9.4016.cap/magw/leptones.1"}
  \b{@@V @RawTableNum "9.4052.cap/magw/leptones.1"}}}

{@@E {
@@D "4912 287"
}
{@NumberMarker
  \a{"9.4052.cap/magw/leptones.1"}
  \b{{{@@V @TablePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawTableNum "9.4052.cap/magw/leptones.1"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "4557 265"
}
{@Table
  \a{"9.4052.cap/magw/leptones.1"}
  \b{Funciones radiales de Mathieu}
{}} } }
}
{@@V @TableVal} } }
}
{@TitleMarker
  \a{"9.4052.cap/magw/leptones.1"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "63 5"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "5783 338"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.libro.lout.43"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.libro.lout.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/ondaEscalar.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
@@D "63 5"
}
{@@V @TableCounterIncrement "9.4052.cap/magw/leptones.2"} } }
}
{@@V @TableCounterMarker
  \a{"9.4016.cap/magw/leptones.2"}
  \b{@@V @RawTableNum "9.4052.cap/magw/leptones.2"}}}

{@@E {
@@D "7503 434"
}
{@NumberMarker
  \a{"9.4052.cap/magw/leptones.2"}
  \b{{{@@V @TablePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawTableNum "9.4052.cap/magw/leptones.2"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "4557 265"
}
{@Table
  \a{"9.4052.cap/magw/leptones.2"}
  \b{Funciones angulares de Mathieu}
{}} } }
}
{@@V @TableVal} } }
}
{@TitleMarker
  \a{"9.4052.cap/magw/leptones.2"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "63 5"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.libro.lout.43"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.libro.lout.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/ondaEscalar.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}}

{@@E {
@@D "4557 265"
}
{@Figure
  \a{"9.3806.cap/magw/leptones.1"}
  \b{Solución tipo II bis.}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "63 5"
}
{@@V @FigureCounterIncrement "9.3806.cap/magw/leptones.1"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/magw/leptones.1"}
  \b{@@V @RawFigureNum "9.3806.cap/magw/leptones.1"}}}

{@@E {
@@D "11543 669"
}
{@NumberMarker
  \a{"9.3806.cap/magw/leptones.1"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/magw/leptones.1"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "4557 265"
}
{@Figure
  \a{"9.3806.cap/magw/leptones.1"}
  \b{Solución tipo II bis.}
  \i{TryAfterLine}
{4 @Scale {@IncludeGraphic "img/fig28.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/magw/leptones.1"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "63 5"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
@@D "8247 474"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.libro.lout.43"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.libro.lout.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/ondaEscalar.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@@V @SubSubSectionList
  \a{"10.290.cap/magw/leptones.3"}
3}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "15760 911"
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ @LInput }} } }
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.3"}
  \b{Solución numérica.}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "15959 927"
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.3"}
  \b{Solución numérica.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1258.cap/magw/leptones.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Slope}
  \h{@@V @SubSubSectionHeadingBreak}
  \i{@Num @@V @SubSubSectionHeadingFormat @Body}
  \k{No}
  \l{@@V @SubSubSectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SubSubSectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SubSubSectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @SubSectionShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{No}
  newpage{No}
@@V @Body} } }
 }
{@@E {
{ @@A { @@E {
@@D "16496 956"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1258.cap/magw/leptones.3"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "16496 956"
}
{@TitleMarker
  \a{"10.1258.cap/magw/leptones.3"}
  \b{@@V title}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ @LInput }} } }
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.3"}
  \b{Solución numérica.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/magw/leptones.2"}
  \b{Estimación numérica del parámetro a (-100)}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "17541 1018"
}
{@@V @FigureCounterIncrement "9.3806.cap/magw/leptones.2"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/magw/leptones.2"}
  \b{@@V @RawFigureNum "9.3806.cap/magw/leptones.2"}}}

{@@E {
@@D "18237 1057"
}
{@NumberMarker
  \a{"9.3806.cap/magw/leptones.2"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/magw/leptones.2"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "17457 1012"
}
{@Figure
  \a{"9.3806.cap/magw/leptones.2"}
  \b{Estimación numérica del parámetro a (-100)}
  \i{TryAfterLine}
{{0.7} @Scale {@IncludeGraphic "img/fig38.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/magw/leptones.2"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "17541 1018"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.libro.lout.43"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.libro.lout.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/ondaEscalar.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ @LInput }} } }
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.3"}
  \b{Solución numérica.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/magw/leptones.3"}
  \b{Parámetro a}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "22961 1332"
}
{@@V @FigureCounterIncrement "9.3806.cap/magw/leptones.3"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/magw/leptones.3"}
  \b{@@V @RawFigureNum "9.3806.cap/magw/leptones.3"}}}

{@@E {
@@D "23626 1371"
}
{@NumberMarker
  \a{"9.3806.cap/magw/leptones.3"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/magw/leptones.3"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "22877 1326"
}
{@Figure
  \a{"9.3806.cap/magw/leptones.3"}
  \b{Parámetro a}
  \i{TryAfterLine}
{3 @Scale {@IncludeGraphic "img/fig41.eps"}
//{@DisplayGap} 3 @Scale {@IncludeGraphic "img/fig40.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/magw/leptones.3"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "22961 1332"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.libro.lout.43"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.libro.lout.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/ondaEscalar.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ @LInput }} } }
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.3"}
  \b{Solución numérica.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/magw/leptones.4"}
  \b{Parámetro a}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "28686 1668"
}
{@@V @FigureCounterIncrement "9.3806.cap/magw/leptones.4"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/magw/leptones.4"}
  \b{@@V @RawFigureNum "9.3806.cap/magw/leptones.4"}}}

{@@E {
@@D "29351 1707"
}
{@NumberMarker
  \a{"9.3806.cap/magw/leptones.4"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/magw/leptones.4"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "28602 1662"
}
{@Figure
  \a{"9.3806.cap/magw/leptones.4"}
  \b{Parámetro a}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/fig42.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/magw/leptones.4"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "28686 1668"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.libro.lout.43"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.libro.lout.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/ondaEscalar.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ @LInput }} } }
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.3"}
  \b{Solución numérica.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/magw/leptones.5"}
  \b{Solución cualitativa tipo III para q=-20}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "34665 2024"
}
{@@V @FigureCounterIncrement "9.3806.cap/magw/leptones.5"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/magw/leptones.5"}
  \b{@@V @RawFigureNum "9.3806.cap/magw/leptones.5"}}}

{@@E {
@@D "35359 2063"
}
{@NumberMarker
  \a{"9.3806.cap/magw/leptones.5"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/magw/leptones.5"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "34581 2018"
}
{@Figure
  \a{"9.3806.cap/magw/leptones.5"}
  \b{Solución cualitativa tipo III para q=-20}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/fig43.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/magw/leptones.5"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "34665 2024"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.libro.lout.43"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.libro.lout.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/ondaEscalar.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.14"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}}

{@@E {
@@D "34581 2018"
}
{@Figure
  \a{"9.3806.cap/magw/leptones.6"}
  \b{Solución tipo III. Posición del cdg}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "34665 2024"
}
{@@V @FigureCounterIncrement "9.3806.cap/magw/leptones.6"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/magw/leptones.6"}
  \b{@@V @RawFigureNum "9.3806.cap/magw/leptones.6"}}}

{@@E {
@@D "41068 2404"
}
{@NumberMarker
  \a{"9.3806.cap/magw/leptones.6"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/magw/leptones.6"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "34581 2018"
}
{@Figure
  \a{"9.3806.cap/magw/leptones.6"}
  \b{Solución tipo III. Posición del cdg}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/fig44.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/magw/leptones.6"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "34665 2024"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.libro.lout.43"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.libro.lout.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/ondaEscalar.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.14"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.16"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ @LInput }} } }
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.3"}
  \b{Solución numérica.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/magw/leptones.7"}
  \b{Las combinaciones lineales de las soluciones tipo III conformarían al electrón.}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "47030 2763"
}
{@@V @FigureCounterIncrement "9.3806.cap/magw/leptones.7"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/magw/leptones.7"}
  \b{@@V @RawFigureNum "9.3806.cap/magw/leptones.7"}}}

{@@E {
@@D "47763 2802"
}
{@NumberMarker
  \a{"9.3806.cap/magw/leptones.7"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/magw/leptones.7"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "46946 2757"
}
{@Figure
  \a{"9.3806.cap/magw/leptones.7"}
  \b{Las combinaciones lineales de las soluciones tipo III conformarían al electrón.}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/fig45.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/magw/leptones.7"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "47030 2763"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.libro.lout.43"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.libro.lout.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/ondaEscalar.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.14"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.16"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.18"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
@@D "47030 2763"
}
{@LUse @BookSetup} } }
}
{@@V @SubSubSectionList
  \a{"10.290.cap/magw/leptones.4"}
4}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "53997 3176"
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ @LInput }} } }
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.4"}
  \b{Interpretación de los resultados.}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "54126 3186"
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.4"}
  \b{Interpretación de los resultados.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1258.cap/magw/leptones.4"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Slope}
  \h{@@V @SubSubSectionHeadingBreak}
  \i{@Num @@V @SubSubSectionHeadingFormat @Body}
  \k{No}
  \l{@@V @SubSubSectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SubSubSectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SubSubSectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @SubSectionShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{No}
  newpage{No}
@@V @Body} } }
 }
{@@E {
{ @@A { @@E {
@@D "54679 3215"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1258.cap/magw/leptones.4"}
  \b{@@V @ShortNum}}}

{@@E {
@@D "54679 3215"
}
{@TitleMarker
  \a{"10.1258.cap/magw/leptones.4"}
  \b{@@V title}}}

{@@E {
@@D "47030 2763"
}
{{} @@V @SendRef olive}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ @LInput }} } }
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.4"}
  \b{Interpretación de los resultados.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/magw/leptones.8"}
  \b{Apariencia de  las dimensiones compactadas. Nótese que no son trayectorias reales, sino la aproximación de rayo de las vibraciones.}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "55794 3282"
}
{@@V @FigureCounterIncrement "9.3806.cap/magw/leptones.8"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/magw/leptones.8"}
  \b{@@V @RawFigureNum "9.3806.cap/magw/leptones.8"}}}

{@@E {
@@D "56594 3321"
}
{@NumberMarker
  \a{"9.3806.cap/magw/leptones.8"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/magw/leptones.8"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "55710 3276"
}
{@Figure
  \a{"9.3806.cap/magw/leptones.8"}
  \b{Apariencia de  las dimensiones compactadas. Nótese que no son trayectorias reales, sino la aproximación de rayo de las vibraciones.}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/fig46.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/magw/leptones.8"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "55794 3282"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.libro.lout.43"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.libro.lout.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/ondaEscalar.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.14"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.16"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.18"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.20"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@SubSection
  \a{"10.1227.cap/magw/leptones.1"}
  \b{Solución para las dimensiones compactadas. Leptones.}
{ @LInput }} } }
}
{@SubSubSection
  \a{"10.1258.cap/magw/leptones.4"}
  \b{Interpretación de los resultados.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/magw/leptones.9"}
  \b{Conjunto de soluciones posibles}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "63276 3722"
}
{@@V @FigureCounterIncrement "9.3806.cap/magw/leptones.9"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/magw/leptones.9"}
  \b{@@V @RawFigureNum "9.3806.cap/magw/leptones.9"}}}

{@@E {
@@D "63976 3761"
}
{@NumberMarker
  \a{"9.3806.cap/magw/leptones.9"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/magw/leptones.9"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "63192 3716"
}
{@Figure
  \a{"9.3806.cap/magw/leptones.9"}
  \b{Conjunto de soluciones posibles}
  \i{TryAfterLine}
{{0.5} @Scale {@IncludeGraphic "img/fig48.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/magw/leptones.9"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "63276 3722"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.2"}
  \b{Matter as gravitational waves}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.libro.lout.3"}
  \b{Las partículas como pulsaciones gravitomagnéticas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.libro.lout.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.libro.lout.43"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.libro.lout.3"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/ondaEscalar.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.2"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.14"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.16"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.18"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.20"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/magw/leptones.22"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.libro.lout.3"}
  \f{@Prefix}}}

