{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.3"}
  \b{Y de nuevo al principio, el éter.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/eter/cosmologia.1"}
  \b{Un postulado cosmológico: el Big Bang como toro de vorticidad y su evolución}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "7 1"
}
{@Section
  \a{"10.1196.cap/eter/cosmologia.1"}
  \b{Un postulado cosmológico: el Big Bang como toro de vorticidad y su evolución}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/eter/cosmologia.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "442 27"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/eter/cosmologia.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/eter/cosmologia.1"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "470 29"
 }
{@@E {
{ @@A { @@E {
@@D "470 29"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1196.cap/eter/cosmologia.1"}
  \b{@@V @ShortNum}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "470 29"
}
{@@V @ContentsStuff} } }
}
{Yes @@V @ContentsEntry
  \a{@@V contentsindent}
  \b{"10.1196.cap/eter/cosmologia.1"}
  \c{@@V @LongNum}
  \d{@@V initiallanguage @Language @@V title}
  \e{@PageOf "10.1196.cap/eter/cosmologia.1"}} } }
}
{@@V @SendContents @@V @ContentsItem
  \a{@@V indent}
  \b{"10.1196.cap/eter/cosmologia.1"}
  \c{@@V number}
  \d{@@V title}
  \e{@@V pagenum}
  \f{@@V pregap}
  \g{@@V postgap}}}

{@@E {
@@D "470 29"
}
{@TitleMarker
  \a{"10.1196.cap/eter/cosmologia.1"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "470 29"
}
{Yes @BeginDisplayCounter @@V @ShortNum} } }
 }
{@@E {
{ @@A { @@E {
@@D "2356 132"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V @NumDispCounterMarker
  \a{"4.1429.cap/eter/cosmologia.1"}
  \b{@@V prefix @Join 0}}}

{@@E {
@@D "35 3"
}
{@@V @SubSectionList
  \a{"10.283.cap/eter/cosmologia.1"}
1}}

{@@E {
{ @@A { @@E {
@@D "7 1"
}
{@Section
  \a{"10.1196.cap/eter/cosmologia.1"}
  \b{Un postulado cosmológico: el Big Bang como toro de vorticidad y su evolución}
{ @LInput }} } }
}
{@SubSection
  \a{"10.1227.cap/eter/cosmologia.1"}
  \b{El toro de vorticidad}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "2688 157"
}
{@SubSection
  \a{"10.1227.cap/eter/cosmologia.1"}
  \b{El toro de vorticidad}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1227.cap/eter/cosmologia.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SubSectionHeadingBreak}
  \i{@Num @@V @SubSectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SubSectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SubSectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SubSectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @SectionShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{No}
  newpage{No}
@@V @Body} } }
 }
{@@E {
{ @@A { @@E {
@@D "2969 171"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1227.cap/eter/cosmologia.1"}
  \b{@@V @ShortNum}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2969 171"
}
{@@V @ContentsStuff} } }
}
{Yes @@V @ContentsEntry
  \a{@@V contentsindent}
  \b{"10.1227.cap/eter/cosmologia.1"}
  \c{@@V @LongNum}
  \d{@@V initiallanguage @Language @@V title}
  \e{@PageOf "10.1227.cap/eter/cosmologia.1"}} } }
}
{@@V @SendContents @@V @ContentsItem
  \a{@@V indent}
  \b{"10.1227.cap/eter/cosmologia.1"}
  \c{@@V number}
  \d{@@V title}
  \e{@@V pagenum}
  \f{@@V pregap}
  \g{@@V postgap}}}

{@@E {
@@D "2969 171"
}
{@TitleMarker
  \a{"10.1227.cap/eter/cosmologia.1"}
  \b{@@V title}}}

{@@E {
@@D "35 3"
}
{@@V @SubSectionList
  \a{"10.283.cap/eter/cosmologia.2"}
2}}

{@@E {
@@D "2688 157"
}
{@SubSection
  \a{"10.1227.cap/eter/cosmologia.2"}
  \b{Compresión supersónica colisional. Cristalización y origen de las pulsaciones y la masa.}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "2688 157"
}
{@SubSection
  \a{"10.1227.cap/eter/cosmologia.2"}
  \b{Compresión supersónica colisional. Cristalización y origen de las pulsaciones y la masa.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1227.cap/eter/cosmologia.2"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SubSectionHeadingBreak}
  \i{@Num @@V @SubSectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SubSectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SubSectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SubSectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @SectionShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{No}
  newpage{No}
@@V @Body} } }
 }
{@@E {
{ @@A { @@E {
@@D "4654 265"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1227.cap/eter/cosmologia.2"}
  \b{@@V @ShortNum}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "4654 265"
}
{@@V @ContentsStuff} } }
}
{Yes @@V @ContentsEntry
  \a{@@V contentsindent}
  \b{"10.1227.cap/eter/cosmologia.2"}
  \c{@@V @LongNum}
  \d{@@V initiallanguage @Language @@V title}
  \e{@PageOf "10.1227.cap/eter/cosmologia.2"}} } }
}
{@@V @SendContents @@V @ContentsItem
  \a{@@V indent}
  \b{"10.1227.cap/eter/cosmologia.2"}
  \c{@@V number}
  \d{@@V title}
  \e{@@V pagenum}
  \f{@@V pregap}
  \g{@@V postgap}}}

{@@E {
@@D "4654 265"
}
{@TitleMarker
  \a{"10.1227.cap/eter/cosmologia.2"}
  \b{@@V title}}}

{@@E {
@@D "35 3"
}
{@@V @SubSectionList
  \a{"10.283.cap/eter/cosmologia.3"}
3}}

{@@E {
@@D "2688 157"
}
{@SubSection
  \a{"10.1227.cap/eter/cosmologia.3"}
  \b{Bifurcación dimensional. Desgarro expansivo y congelación de la contracción de las dimensiones compactadas.}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
@@D "2688 157"
}
{@SubSection
  \a{"10.1227.cap/eter/cosmologia.3"}
  \b{Bifurcación dimensional. Desgarro expansivo y congelación de la contracción de las dimensiones compactadas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1227.cap/eter/cosmologia.3"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SubSectionHeadingBreak}
  \i{@Num @@V @SubSectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SubSectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SubSectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SubSectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @SectionShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{No}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{No}
  newpage{No}
@@V @Body} } }
 }
{@@E {
{ @@A { @@E {
@@D "6425 359"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1227.cap/eter/cosmologia.3"}
  \b{@@V @ShortNum}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "6425 359"
}
{@@V @ContentsStuff} } }
}
{Yes @@V @ContentsEntry
  \a{@@V contentsindent}
  \b{"10.1227.cap/eter/cosmologia.3"}
  \c{@@V @LongNum}
  \d{@@V initiallanguage @Language @@V title}
  \e{@PageOf "10.1227.cap/eter/cosmologia.3"}} } }
}
{@@V @SendContents @@V @ContentsItem
  \a{@@V indent}
  \b{"10.1227.cap/eter/cosmologia.3"}
  \c{@@V number}
  \d{@@V title}
  \e{@@V pagenum}
  \f{@@V pregap}
  \g{@@V postgap}}}

{@@E {
@@D "6425 359"
}
{@TitleMarker
  \a{"10.1227.cap/eter/cosmologia.3"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "470 29"
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "7932 438"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.cap/eter/cosmologia.2"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/eter/cosmologia.1"}
  \f{{} @Join @@V @ShortNum}}}

