{ @Reference
@Tag { alcerro}
@Type { Article}
@Author { Alcerro Mena, Juan Carlos}
@Title { Euclidean Equivalent of Minkowskis Space-Time Theory and the Corresponding Model of Elementary Particles (Cuantex Model) }
@Publisher {  }
@Edition {  }
@Year { 2018 }
}

 
{ @Reference
@Tag { ernesto}
@Type { Article}
@Author { López González, Ernesto}
@Title { Matter as gravitational waves. Dark Energy.}
@Publisher {  }
@Edition {  }
@Year { 2014 }
}

{ @Reference
@Tag { botton}
@Type { Article}
@Author { Valery Botton, Brahim Moudjed, Daniel Henry, Hamda Ben-Hadid, Jean-Paul Garandet}
@Title { Scaling and dimensional analysis of acoustic streaming jets}
@Publisher {  }
@Edition {  }
@Year { 2014 }
}

{ @Reference
@Tag { palazzi}
@Type { Article}
@Author { Palazzi}
@Title { Patterns in the Meson Mass Spectrum }
@Publisher {  }
@Edition {  }
@Year { 2004 }
}    
 
 
{ @Reference
@Tag { carmignotto}
@Type { Article}
@Author { Marco Carmignotto, Tanja Horn, and Gerald A. Miller}
@Title { Pion transverse charge density and the edge of hadrons    }
@Publisher {  }
@Edition {  }
@Year { 2014 }
} 

  

{ @Reference
@Tag { slac}
@Type { Article}
@Author { Martin Breidenbach(MIT, LNS), Jerome I. Friedman(MIT, LNS), Henry W. Kendall(MIT, LNS), Elliott D. Bloom(SLAC), D.H. Coward(SLAC)}
@Title { Observed behavior of highly inelastic electron-proton scattering   }
@Publisher { SLAC-PUB-650 }
@Edition {  }
@Year { 1969}
}


{ @Reference
@Tag { miller}
@Type { Article}
@Author { Miller}
@Title {  Charge densities of the neutron and proton }
@Publisher { }
@Edition {  }
@Year { 2007}
}


  

{ @Reference
@Tag { puckett}
@Type { Article}
@Author { Puckett et al.}
@Title {  Final Analysis of Proton Form Factor Ratio Data at Q²=4.0, 4.8 and 5.6 GeV  }
@Publisher { }
@Edition {  }
@Year { 2018}
} 


{ @Reference
@Tag { boster}
@Type { Article}
@Author { Boster}
@Title {  An Empirical Fit to the Nucleon Electromagnetic Form Factors  }
@Publisher { }
@Edition {  }
@Year { 1994 }
} 

   

{ @Reference
@Tag { arrington}
@Type { Article}
@Author { Arrington}
@Title {  Proton and neutron electromagnetic form factors and uncertainties }
@Publisher { }
@Edition {  }
@Year { 2017 }
}

 

{ @Reference
@Tag { kostoulas}
@Type { Article}
@Author {Kostoulas}
@Title {  Muon-proton Deep elastic Scattering . }
@Publisher { }
@Edition {  }
@Year { 1974}
}


   

{ @Reference
@Tag { gao}
@Type { Article}
@Author {Haiyan Gao}
@Title {  Review on Nucleon Electromagnetic Form Factor }
@Publisher { }
@Edition {  }
@Year { 2010 }
}


 
 
 
 { @Reference
@Tag { jones}
@Type { Article}
@Author {Jones}
@Title {  G @Sub {Ep}  @Math {slash} G @Sub {M p} ratio by polarization transfer in vec{e}p->evec{p}  }
@Publisher { }
@Edition {  }
@Year { 1999 }
}

  
 { @Reference
@Tag { amendolia}
@Type { Article}
@Author {Amendolia}
@Title { A measurement of the kaon charge radius  }
@Publisher { }
@Edition {  }
@Year { 1986 }
}


 { @Reference
@Tag { dally}
@Type { Article}
@Author {B. Dally }
@Title { Direct measurement of the negative kaon form factor.  }
@Publisher { }
@Edition {  }
@Year {  }
}


 { @Reference
@Tag { ghah}
@Type { Article}
@Author {N. Ghahramany }
@Title {  Form Factor and Cross Section Calculation in Charged Kaon Electroproduction at @Math {Q² =1.9  2.35(GeV slash c)²}     }
@Publisher { }
@Edition {  }
@Year { 2015 }
}

 { @Reference
@Tag { zitterbewegung}
@Type { Article}
@Author {E. Schrödinger }
@Title {  Über die kräftefreie Bewegung in der relativistischen Quantenmechanik }
@Publisher { Berliner Ber. }
@Edition {  }
@Year { 1930 }
}

 { @Reference
@Tag { mclachlan}
@Type { Article}
@Author {N.W. Mclanchlan }
@Title { Theory and aplications of Mathieu Functions }
@Publisher { Dsc (Enginnering) London }
@Edition {  }
@Year { 1947 }
}


 { @Reference
@Tag { olive}
@Type { Article}
@Author {Olive, K.A.; et al. }
@Title { 2014 Review of Particle Physics. }
@Publisher { Particle Data Group }
@Edition {  }
@Year { 2014 }
}
 

 { @Reference
@Tag { toledo}
@Type { Article}
@Author {Garcia Gudiño y Toledo Sanchez}
@Title { Determination of the magnetic dipole moment of the rho meson using 4 pion electroproduction data }
@Publisher {  Int.J.Mod.Phys.Conf.Ser.}
@Edition {  }
@Year { 2013 }
}

 
 { @Reference
@Tag { hofstader}
@Type { Book}
@Author {Herman and Hofstader}
@Title { High-Energy electron scattering tables }
@Publisher {  Standford University Press}
@Edition {  }
@Year { 1960 }
}

 { @Reference
@Tag { dstate}
@Type { Article}
@Author { N.L. Rodning, L.D. Knutson}
@Title { Asymptotic D-state to S-state ratio of the deuteron }
@Publisher { Phys.Rev.C 41}
@Edition {  }
@Year { 1990 }
}

 { @Reference
@Tag { liquidcrystal}
@Type { Article}
@Author { S. Chandrasekhar}
@Title { Propagation of elastic waves on liquid crystals }
@Publisher { Royal Society}
@Edition {  }
@Year { 1964 }
}




