{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "7 1"
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "398 27"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/dcarga.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "426 29"
 }
{@@E {
{ @@A { @@E {
@@D "426 29"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{@@V @ShortNum}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "426 29"
}
{@@V @ContentsStuff} } }
}
{Yes @@V @ContentsEntry
  \a{@@V contentsindent}
  \b{"10.1196.cap/hadr/dcarga.1"}
  \c{@@V @LongNum}
  \d{@@V initiallanguage @Language @@V title}
  \e{@PageOf "10.1196.cap/hadr/dcarga.1"}} } }
}
{@@V @SendContents @@V @ContentsItem
  \a{@@V indent}
  \b{"10.1196.cap/hadr/dcarga.1"}
  \c{@@V number}
  \d{@@V title}
  \e{@@V pagenum}
  \f{@@V pregap}
  \g{@@V postgap}}}

{@@E {
@@D "426 29"
}
{@TitleMarker
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "426 29"
}
{Yes @BeginDisplayCounter @@V @ShortNum} } }
 }
{@@E {
{ @@A { @@E {
@@D "2242 132"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V @NumDispCounterMarker
  \a{"4.1429.cap/hadr/dcarga.1"}
  \b{@@V prefix @Join 0}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "7 1"
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@RawList
  \a{--}} } }
}
{@@V @MakeList 1} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.cap/hadr/dcarga.2"}
  \b{@@V type 1}}}

{@@E {
@@D "2529 153"
}
{@@V listitem
  \a{"4.1748.cap/hadr/dcarga.1"}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2515 152"
}
{@@V @MakeList 2} } }
}
{@@V @NormalItem} } }
}
{@NumberMarker
  \a{"4.1200.cap/hadr/dcarga.4"}
  \b{@@V type 2}}}

{@@E {
@@D "2529 153"
}
{@@V listitem
  \a{"4.1748.cap/hadr/dcarga.2"}
???}}

{@@E {
@@D "2529 153"
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.1"}
  \b{Densidad de carga del protón}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/dcarga.1"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/dcarga.1"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/dcarga.1"}}}

{@@E {
@@D "3267 209"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/dcarga.1"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/dcarga.1"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2529 153"
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.1"}
  \b{Densidad de carga del protón}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/Libro-img070.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/dcarga.1"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "3281 210"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "4137 255"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/dcarga.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}}

{@@E {
@@D "2529 153"
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.2"}
  \b{Densidad teórica transversal de carga}
  \i{TryAfterLine}
???}}

{@@E {
@@D "3281 210"
}
{{} @@V @SendRef miller}}

{@@E {
@@D "2529 153"
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.3"}
  \b{Comparación con los resultados experimentales de Miller}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "3281 210"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/dcarga.2"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/dcarga.2"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/dcarga.2"}}}

{@@E {
@@D "6038 365"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/dcarga.2"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/dcarga.2"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2529 153"
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.2"}
  \b{Densidad teórica transversal de carga}
  \i{TryAfterLine}
{{2.5} @Scale {@IncludeGraphic "img/Libro-img071.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/dcarga.2"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "3281 210"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/dcarga.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
@@D "3281 210"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/dcarga.3"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/dcarga.3"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/dcarga.3"}}}

{@@E {
@@D "9737 571"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/dcarga.3"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/dcarga.3"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2529 153"
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.3"}
  \b{Comparación con los resultados experimentales de Miller}
  \i{TryAfterLine}
{2 @Scale {@IncludeGraphic "img/Libro-img072.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/dcarga.3"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "3281 210"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
@@D "6862 406"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/dcarga.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.4"}
  \b{Densidad de carga del neutrón}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "13748 796"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/dcarga.4"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/dcarga.4"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/dcarga.4"}}}

{@@E {
@@D "14201 825"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/dcarga.4"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/dcarga.4"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "13692 792"
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.4"}
  \b{Densidad de carga del neutrón}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/Libro-img073.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/dcarga.4"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "13748 796"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/dcarga.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}}

{@@E {
@@D "13692 792"
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.5"}
  \b{Densidad transversal de carga}
  \i{TryAfterLine}
???}}

{@@E {
@@D "13692 792"
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.6"}
  \b{Tamaño de los principales bariones}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "13748 796"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/dcarga.5"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/dcarga.5"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/dcarga.5"}}}

{@@E {
@@D "18785 1091"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/dcarga.5"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/dcarga.5"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "13692 792"
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.5"}
  \b{Densidad transversal de carga}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/Libro-img075.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/dcarga.5"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "13748 796"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/dcarga.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
@@D "13748 796"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/dcarga.6"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/dcarga.6"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/dcarga.6"}}}

{@@E {
@@D "23422 1360"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/dcarga.6"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/dcarga.6"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "13692 792"
}
{@Figure
  \a{"9.3806.cap/hadr/dcarga.6"}
  \b{Tamaño de los principales bariones}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/fig94.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/dcarga.6"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "13748 796"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
@@D "19603 1132"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/dcarga.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.14"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{@Prefix}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "13748 796"
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Orbitales y distribución interna de carga.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/dcarga.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "28310 1644"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/dcarga.2"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/dcarga.1"}
  \f{{} @Join @@V @ShortNum}}}

