{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Factor de forma del kaón}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "7 1"
}
{@Section
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Factor de forma del kaón}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "379 27"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/fkaon.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "407 29"
 }
{@@E {
{ @@A { @@E {
@@D "407 29"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{@@V @ShortNum}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "407 29"
}
{@@V @ContentsStuff} } }
}
{Yes @@V @ContentsEntry
  \a{@@V contentsindent}
  \b{"10.1196.cap/hadr/fkaon.1"}
  \c{@@V @LongNum}
  \d{@@V initiallanguage @Language @@V title}
  \e{@PageOf "10.1196.cap/hadr/fkaon.1"}} } }
}
{@@V @SendContents @@V @ContentsItem
  \a{@@V indent}
  \b{"10.1196.cap/hadr/fkaon.1"}
  \c{@@V number}
  \d{@@V title}
  \e{@@V pagenum}
  \f{@@V pregap}
  \g{@@V postgap}}}

{@@E {
@@D "407 29"
}
{@TitleMarker
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "407 29"
}
{Yes @BeginDisplayCounter @@V @ShortNum} } }
 }
{@@E {
{ @@A { @@E {
@@D "2196 132"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V @NumDispCounterMarker
  \a{"4.1429.cap/hadr/fkaon.1"}
  \b{@@V prefix @Join 0}}}

{@@E {
@@D "49 4"
}
{{} @@V @SendRef palazzi}}

{@@E {
{ @@A { @@E {
@@D "7 1"
}
{@Section
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Factor de forma del kaón}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/fkaon.1"}
  \b{Densidad de carga teórica del kaón.}
  \i{TryAfterLine}
???}}

{@@E {
@@D "49 4"
}
{{} @@V @SendRef amendolia}}

{@@E {
@@D "49 4"
}
{{} @@V @SendRef dally}}

{@@E {
@@D "2488 155"
}
{@Figure
  \a{"9.3806.cap/hadr/fkaon.2"}
  \b{Factor de forma a bajo q @Sup 2}
  \i{TryAfterLine}
???}}

{@@E {
@@D "49 4"
}
{{} @@V @SendRef ghah}}

{@@E {
@@D "2488 155"
}
{@Figure
  \a{"9.3806.cap/hadr/fkaon.3"}
  \b{Factor de forma a q @Sup 2 más elevados}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fkaon.1"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fkaon.1"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fkaon.1"}}}

{@@E {
@@D "3130 203"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fkaon.1"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fkaon.1"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2488 155"
}
{@Figure
  \a{"9.3806.cap/hadr/fkaon.1"}
  \b{Densidad de carga teórica del kaón.}
  \i{TryAfterLine}
{{2.5} @Scale {@IncludeGraphic "img/fig64.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fkaon.1"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "49 4"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Factor de forma del kaón}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "3916 243"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/fkaon.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fkaon.2"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fkaon.2"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fkaon.2"}}}

{@@E {
@@D "5452 330"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fkaon.2"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fkaon.2"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2488 155"
}
{@Figure
  \a{"9.3806.cap/hadr/fkaon.2"}
  \b{Factor de forma a bajo q @Sup 2}
  \i{TryAfterLine}
{{2.3} @Scale {@IncludeGraphic "img/fig65.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fkaon.2"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "49 4"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
@@D "4014 250"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Factor de forma del kaón}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "6304 376"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/fkaon.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fkaon.3"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fkaon.3"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fkaon.3"}}}

{@@E {
@@D "8010 472"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fkaon.3"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fkaon.3"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "8024 473"
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Factor de forma del kaón}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/fkaon.3"}
  \b{Factor de forma a q @Sup 2 más elevados}
  \i{TryAfterLine}
{{2.3} @Scale {@IncludeGraphic "img/fig66.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fkaon.3"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "8024 473"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Factor de forma del kaón}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "9454 560"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/fkaon.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}}

{@@E {
@@D "8525 497"
}
{@Figure
  \a{"9.3806.cap/hadr/fkaon.4"}
  \b{Vida media de los mesones vs Múltiplos de masa del Kaón}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "8024 473"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fkaon.4"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fkaon.4"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fkaon.4"}}}

{@@E {
@@D "11483 674"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fkaon.4"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fkaon.4"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "8525 497"
}
{@Figure
  \a{"9.3806.cap/hadr/fkaon.4"}
  \b{Vida media de los mesones vs Múltiplos de masa del Kaón}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/fig67.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fkaon.4"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "8024 473"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Factor de forma del kaón}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "12721 750"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/fkaon.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Factor de forma del kaón}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/fkaon.5"}
  \b{Factor de forma teórico vs Datos experimentales}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "14825 868"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fkaon.5"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fkaon.5"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fkaon.5"}}}

{@@E {
@@D "15276 897"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fkaon.5"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fkaon.5"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "14769 864"
}
{@Figure
  \a{"9.3806.cap/hadr/fkaon.5"}
  \b{Factor de forma teórico vs Datos experimentales}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/fig68.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fkaon.5"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "14825 868"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Factor de forma del kaón}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "16651 985"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/fkaon.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{@Prefix}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "14783 865"
}
{@Section
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Factor de forma del kaón}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fkaon.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "18878 1108"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fkaon.2"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fkaon.1"}
  \f{{} @Join @@V @ShortNum}}}

