{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Fuerza nuclear fuerte residual aparente}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "7 1"
}
{@Section
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Fuerza nuclear fuerte residual aparente}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "397 27"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/fnuclear.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fnuclear.1"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "425 29"
 }
{@@E {
{ @@A { @@E {
@@D "425 29"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{@@V @ShortNum}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "425 29"
}
{@@V @ContentsStuff} } }
}
{Yes @@V @ContentsEntry
  \a{@@V contentsindent}
  \b{"10.1196.cap/hadr/fnuclear.1"}
  \c{@@V @LongNum}
  \d{@@V initiallanguage @Language @@V title}
  \e{@PageOf "10.1196.cap/hadr/fnuclear.1"}} } }
}
{@@V @SendContents @@V @ContentsItem
  \a{@@V indent}
  \b{"10.1196.cap/hadr/fnuclear.1"}
  \c{@@V number}
  \d{@@V title}
  \e{@@V pagenum}
  \f{@@V pregap}
  \g{@@V postgap}}}

{@@E {
@@D "425 29"
}
{@TitleMarker
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "425 29"
}
{Yes @BeginDisplayCounter @@V @ShortNum} } }
 }
{@@E {
{ @@A { @@E {
@@D "2256 132"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V @NumDispCounterMarker
  \a{"4.1429.cap/hadr/fnuclear.1"}
  \b{@@V prefix @Join 0}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Fuerza nuclear fuerte residual aparente}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/fnuclear.1"}
  \b{Potencial electrofuerte}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fnuclear.1"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fnuclear.1"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fnuclear.1"}}}

{@@E {
@@D "3007 183"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fnuclear.1"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fnuclear.1"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "3021 184"
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Fuerza nuclear fuerte residual aparente}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/fnuclear.1"}
  \b{Potencial electrofuerte}
  \i{TryAfterLine}
{{2.5} @Scale {@IncludeGraphic "img/Libro-img104.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fnuclear.1"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "3021 184"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Fuerza nuclear fuerte residual aparente}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "4197 247"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/fnuclear.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fnuclear.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fnuclear.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fnuclear.1"}
  \f{@Prefix}}}

{@@E {
@@D "3537 208"
}
{@Figure
  \a{"9.3806.cap/hadr/fnuclear.2"}
  \b{Potencial nuclear residual aparente}
  \i{TryAfterLine}
???}}

{@@E {
@@D "3537 208"
}
{@Figure
  \a{"9.3806.cap/hadr/fnuclear.3"}
  \b{Potencial nuclear residual aparente}
  \i{TryAfterLine}
???}}

{@@E {
@@D "3537 208"
}
{@Figure
  \a{"9.3806.cap/hadr/fnuclear.4"}
  \b{Media del potencial electrofuerte sin deformar y deformado. Superposición con datos experimentales}
  \i{TryAfterLine}
???}}

{@@E {
@@D "3537 208"
}
{@Figure
  \a{"9.3806.cap/hadr/fnuclear.5"}
  \b{Superposición con datos experimentales}
  \i{TryAfterLine}
???}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "3551 209"
}
{@Section
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Fuerza nuclear fuerte residual aparente}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "6384 370"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fnuclear.2"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fnuclear.1"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@A { @@E {
@@D "3021 184"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fnuclear.2"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fnuclear.2"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fnuclear.2"}}}

{@@E {
@@D "7473 427"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fnuclear.2"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fnuclear.2"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "3537 208"
}
{@Figure
  \a{"9.3806.cap/hadr/fnuclear.2"}
  \b{Potencial nuclear residual aparente}
  \i{TryAfterLine}
{{2.5} @Scale {@IncludeGraphic "img/Libro-img105.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fnuclear.2"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "3021 184"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Fuerza nuclear fuerte residual aparente}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "8295 467"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fnuclear.2"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fnuclear.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fnuclear.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fnuclear.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
@@D "3021 184"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fnuclear.3"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fnuclear.3"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fnuclear.3"}}}

{@@E {
@@D "9819 551"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fnuclear.3"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fnuclear.3"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "3537 208"
}
{@Figure
  \a{"9.3806.cap/hadr/fnuclear.3"}
  \b{Potencial nuclear residual aparente}
  \i{TryAfterLine}
{{2.5} @Scale {@IncludeGraphic "img/Libro-img106.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fnuclear.3"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "3021 184"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
@@D "8379 473"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Fuerza nuclear fuerte residual aparente}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fnuclear.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "10711 597"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fnuclear.2"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fnuclear.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fnuclear.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fnuclear.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fnuclear.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fnuclear.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
@@D "3021 184"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fnuclear.4"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fnuclear.4"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fnuclear.4"}}}

{@@E {
@@D "12412 690"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fnuclear.4"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fnuclear.4"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "3537 208"
}
{@Figure
  \a{"9.3806.cap/hadr/fnuclear.4"}
  \b{Media del potencial electrofuerte sin deformar y deformado. Superposición con datos experimentales}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/fig62.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fnuclear.4"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "3021 184"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/conclusiones.1"}
  \b{Conclusiones}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/conclusiones.1"}
  \b{Minor}
  \c{}
  \d{Conclusiones}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "13288 730"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/conclusiones.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/conclusiones.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fnuclear.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/conclusiones.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
@@D "3021 184"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fnuclear.5"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fnuclear.5"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fnuclear.5"}}}

{@@E {
@@D "14854 817"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fnuclear.5"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fnuclear.5"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "3537 208"
}
{@Figure
  \a{"9.3806.cap/hadr/fnuclear.5"}
  \b{Superposición con datos experimentales}
  \i{TryAfterLine}
{{2.3} @Scale {@IncludeGraphic "img/fig63.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fnuclear.5"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "3021 184"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
@@D "8379 473"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/conclusiones.1"}
  \b{Conclusiones}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/conclusiones.1"}
  \b{Minor}
  \c{}
  \d{Conclusiones}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "15743 863"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/conclusiones.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/conclusiones.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fnuclear.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/conclusiones.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fnuclear.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/conclusiones.1"}
  \f{@Prefix}}}

