{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "7 1"
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "379 27"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/fpion.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "407 29"
 }
{@@E {
{ @@A { @@E {
@@D "407 29"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{@@V @ShortNum}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "407 29"
}
{@@V @ContentsStuff} } }
}
{Yes @@V @ContentsEntry
  \a{@@V contentsindent}
  \b{"10.1196.cap/hadr/fpion.1"}
  \c{@@V @LongNum}
  \d{@@V initiallanguage @Language @@V title}
  \e{@PageOf "10.1196.cap/hadr/fpion.1"}} } }
}
{@@V @SendContents @@V @ContentsItem
  \a{@@V indent}
  \b{"10.1196.cap/hadr/fpion.1"}
  \c{@@V number}
  \d{@@V title}
  \e{@@V pagenum}
  \f{@@V pregap}
  \g{@@V postgap}}}

{@@E {
@@D "407 29"
}
{@TitleMarker
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "407 29"
}
{Yes @BeginDisplayCounter @@V @ShortNum} } }
 }
{@@E {
{ @@A { @@E {
@@D "2196 132"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V @NumDispCounterMarker
  \a{"4.1429.cap/hadr/fpion.1"}
  \b{@@V prefix @Join 0}}}

{@@E {
@@D "49 4"
}
{{} @@V @SendRef palazzi}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/fpion.1"}
  \b{Densidad de carga teórica del pión.}
  \i{TryAfterLine}
???}}

{@@E {
@@D "2544 159"
}
{{} @@V @SendRef carmignotto}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fpion.1"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fpion.1"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fpion.1"}}}

{@@E {
@@D "3039 193"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fpion.1"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fpion.1"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "3053 194"
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/fpion.1"}
  \b{Densidad de carga teórica del pión.}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/Libro-img096.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fpion.1"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "3053 194"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "4341 269"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/fpion.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fneutron.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{@Prefix}}}

{@@E {
@@D "3554 218"
}
{@Figure
  \a{"9.3806.cap/hadr/fpion.2"}
  \b{Vida media de los mesones vs Múltiplos de masa del Pión}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fpion.2"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fpion.2"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fpion.2"}}}

{@@E {
@@D "6203 374"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fpion.2"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fpion.2"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "6217 375"
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/fpion.2"}
  \b{Vida media de los mesones vs Múltiplos de masa del Pión}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/Libro-img097.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fpion.2"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "6217 375"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "7667 462"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/fpion.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fneutron.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{@Prefix}}}

{@@E {
@@D "6718 399"
}
{@Figure
  \a{"9.3806.cap/hadr/fpion.3"}
  \b{Comparación con densidad experimental de Miller}
  \i{TryAfterLine}
???}}

{@@E {
@@D "6718 399"
}
{@Figure
  \a{"9.3806.cap/hadr/fpion.4"}
  \b{Comparación curva teórica frente a parametrización de Miller}
  \i{TryAfterLine}
???}}

{@@E {
@@D "6718 399"
}
{@Figure
  \a{"9.3806.cap/hadr/fpion.5"}
  \b{90% a @Math { slash } 4 - 10% a @Math { slash } 8}
  \i{TryAfterLine}
???}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "6732 400"
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "10004 594"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.2"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@A { @@E {
@@D "6217 375"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fpion.3"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fpion.3"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fpion.3"}}}

{@@E {
@@D "11067 651"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fpion.3"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fpion.3"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "6718 399"
}
{@Figure
  \a{"9.3806.cap/hadr/fpion.3"}
  \b{Comparación con densidad experimental de Miller}
  \i{TryAfterLine}
{{0.7} @Scale {@IncludeGraphic "img/Libro-img098.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fpion.3"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "6217 375"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "11881 691"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.2"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
@@D "6217 375"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fpion.4"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fpion.4"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fpion.4"}}}

{@@E {
@@D "13373 775"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fpion.4"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fpion.4"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "6718 399"
}
{@Figure
  \a{"9.3806.cap/hadr/fpion.4"}
  \b{Comparación curva teórica frente a parametrización de Miller}
  \i{TryAfterLine}
{{0.6} @Scale {@IncludeGraphic "img/Libro-img099.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fpion.4"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "6217 375"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
@@D "11965 697"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "14271 821"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.2"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/fpion.5"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/fpion.5"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/fpion.5"}}}

{@@E {
@@D "15934 914"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/fpion.5"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/fpion.5"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "15948 915"
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/fpion.5"}
  \b{90% a @Math { slash } 4 - 10% a @Math { slash } 8}
  \i{TryAfterLine}
{{0.6} @Scale {@IncludeGraphic "img/Libro-img100.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/fpion.5"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "15948 915"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.6"}
  \b{Estructura de los Hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Factor de forma del pión}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/fpion.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "17398 1002"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.2"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/fpion.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/fpion.1"}
  \f{@Prefix}}}

