{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ ??? }}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "7 1"
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "389 27"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/hadr.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{{} @Join @@V @ShortNum}}}

{@@E {
{ @@B { @@D "417 29"
 }
{@@E {
{ @@A { @@E {
@@D "417 29"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@NumberMarker
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{@@V @ShortNum}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "417 29"
}
{@@V @ContentsStuff} } }
}
{Yes @@V @ContentsEntry
  \a{@@V contentsindent}
  \b{"10.1196.cap/hadr/hadr.1"}
  \c{@@V @LongNum}
  \d{@@V initiallanguage @Language @@V title}
  \e{@PageOf "10.1196.cap/hadr/hadr.1"}} } }
}
{@@V @SendContents @@V @ContentsItem
  \a{@@V indent}
  \b{"10.1196.cap/hadr/hadr.1"}
  \c{@@V number}
  \d{@@V title}
  \e{@@V pagenum}
  \f{@@V pregap}
  \g{@@V postgap}}}

{@@E {
@@D "417 29"
}
{@TitleMarker
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{@@V title}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "417 29"
}
{Yes @BeginDisplayCounter @@V @ShortNum} } }
 }
{@@E {
{ @@A { @@E {
@@D "2222 132"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V @NumDispCounterMarker
  \a{"4.1429.cap/hadr/hadr.1"}
  \b{@@V prefix @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "7 1"
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.1"}
  \b{Tipo positronio}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/hadr.1"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/hadr.1"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/hadr.1"}}}

{@@E {
@@D "2703 165"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/hadr.1"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/hadr.1"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2465 150"
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.1"}
  \b{Tipo positronio}
  \i{TryAfterLine}
{{0.3} @Scale {@IncludeGraphic "img/Libro-img062.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/hadr.1"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "49 4"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "3469 205"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/hadr.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}}

{@@E {
@@D "2465 150"
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.2"}
  \b{Tipo Helio. Nº epícimas divisible por 4}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/hadr.2"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/hadr.2"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/hadr.2"}}}

{@@E {
@@D "5146 301"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/hadr.2"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/hadr.2"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2465 150"
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.2"}
  \b{Tipo Helio. Nº epícimas divisible por 4}
  \i{TryAfterLine}
{{0.4} @Scale {@IncludeGraphic "img/Libro-img063.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/hadr.2"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "49 4"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/hadr.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}}

{@@E {
@@D "2465 150"
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.3"}
  \b{Número de epícimas par, pero no divisible por 4}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/hadr.3"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/hadr.3"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/hadr.3"}}}

{@@E {
@@D "8935 516"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/hadr.3"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/hadr.3"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "2465 150"
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.3"}
  \b{Número de epícimas par, pero no divisible por 4}
  \i{TryAfterLine}
{{0.4} @Scale {@IncludeGraphic "img/Libro-img064.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/hadr.3"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "49 4"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
@@D "5950 342"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
@@D "9945 574"
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/hadr.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}}

{@@E {
@@D "49 4"
}
{{} @@V @SendRef palazzi}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "49 4"
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.4"}
  \b{Propuesta para el muón}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "49 4"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/hadr.4"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/hadr.4"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/hadr.4"}}}

{@@E {
@@D "12285 711"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/hadr.4"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/hadr.4"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "11870 684"
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.4"}
  \b{Propuesta para el muón}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/Libro-img065.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/hadr.4"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "49 4"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/hadr.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.5"}
  \b{Propuesta para el @Math { pi @Sup 0 }}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "16589 963"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/hadr.5"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/hadr.5"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/hadr.5"}}}

{@@E {
@@D "17039 992"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/hadr.5"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/hadr.5"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "16533 959"
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.5"}
  \b{Propuesta para el @Math { pi @Sup 0 }}
  \i{TryAfterLine}
{{0.31} @Scale {@IncludeGraphic "img/Libro-img066.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/hadr.5"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "16589 963"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/hadr.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}}

{@@E {
@@D "16533 959"
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.6"}
  \b{Propuesta para el @Math { pi sup {} + {} }}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "16589 963"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/hadr.6"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/hadr.6"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/hadr.6"}}}

{@@E {
@@D "21767 1270"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/hadr.6"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/hadr.6"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "16533 959"
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.6"}
  \b{Propuesta para el @Math { pi sup {} + {} }}
  \i{TryAfterLine}
{{1.5} @Scale {@IncludeGraphic "img/Libro-img067.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/hadr.6"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "16589 963"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/hadr.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.14"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.7"}
  \b{Propuesta para el protón}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "26727 1564"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/hadr.7"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/hadr.7"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/hadr.7"}}}

{@@E {
@@D "27164 1593"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/hadr.7"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/hadr.7"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "26671 1560"
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.7"}
  \b{Propuesta para el protón}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/Libro-img068.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/hadr.7"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "26727 1564"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/hadr.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.14"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.16"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.8"}
  \b{Propuesta para el neutrón}
  \i{TryAfterLine}
???}}

{@@E {
{ @@A { @@E {
@@D "32417 1908"
}
{@@V @FigureCounterIncrement "9.3806.cap/hadr/hadr.8"} } }
}
{@@V @FigureCounterMarker
  \a{"9.3770.cap/hadr/hadr.8"}
  \b{@@V @RawFigureNum "9.3806.cap/hadr/hadr.8"}}}

{@@E {
@@D "32855 1937"
}
{@NumberMarker
  \a{"9.3806.cap/hadr/hadr.8"}
  \b{{{@@V @FigurePrefixMarker&&{@@V tag}} @Open {prefix}} @Join {Arabic @@V @Num {@@V @RawFigureNum "9.3806.cap/hadr/hadr.8"}}}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "32361 1904"
}
{@Figure
  \a{"9.3806.cap/hadr/hadr.8"}
  \b{Propuesta para el neutrón}
  \i{TryAfterLine}
{{} @Scale {@IncludeGraphic "img/Libro-img069b.eps"}}} } }
}
{@@V @FigureVal} } }
}
{@TitleMarker
  \a{"9.3806.cap/hadr/hadr.8"}
  \b{@@V @Caption}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "32417 1908"
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @DupRunner} } }
 }
{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
 }
{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Heading} } }
}
{@@V @Run @@V @StartIfMajor} } }
}
{{??} @@V @Do {??}} } }
}
{@@V y}} }
}
{@@V start @Runner
  \g{"9.952.cap/hadr/hadr.1"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{{} @Join @@V @ShortNum}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.4"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.6"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.8"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.10"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.12"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.14"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.16"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.18"}
  \a{@MajorNum}
  \b{@MajorTitle}
  \c{@MinorNum}
  \d{@MinorTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{@Prefix}}}

{@@E {
{ @@B { { @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "32417 1908"
}
{@LUse @BookSetup} } }
}
{@LUse @TblSetup} } }
}
{@Chapter
  \a{"10.1148.libro.lout.5"}
  \b{Los hadrones.}
{ @LInput }} } }
}
{@Section
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Aplicación de la ecuación de onda a las epícimas.}
{ @LInput }} } }
}
{@@V @LargeScaleStructure
  \a{"10.1196.cap/hadr/hadr.1"}
  \b{Minor}
  \c{}
  \d{@@V @Title}
  \e{dft}
  \g{Bold}
  \h{@@V @SectionHeadingBreak}
  \i{@Num @@V @SectionHeadingFormat @Body}
  \k{Yes}
  \l{@@V @SectionContentsIndent}
  \n{Arabic}
  \o{{@@V @SectionList&&preceding} @Tagged @@V @Tag}
  \p{{@@V @SectionList&&{@@V @Tag}} @Open {num}}
  \q{dft}
  \r{@@V @ChapterShortNum}
  \t{@@V @MajorNum}
  \u{@@V @MajorTitle}
  \x{No}
  \y{Yes}
  \z{No}
  intables{No}
  infloaters{No}
  inrunners{Yes}
  newpage{No}
@@V @Body} } }
}
{@@V @Run NonStart} } }
 }
{@@E {
{ @@A { @@E {
@@D "38373 2269"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{NonStart @Runner
  \g{"9.952.cap/hadr/hadr.2"}
  \a{@@V majornum @@V @Dft @@V @LongNum}
  \b{@@V majortitle @@V @Dft @@V @ShortTitle}
  \c{dft @@V @Dft @@V @LongNum}
  \d{dft @@V @Dft @@V @ShortTitle}
  \e{"10.1196.cap/hadr/hadr.1"}
  \f{{} @Join @@V @ShortNum}}}

